name: digit_assignment
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <=4.0.0'

dependencies:
  flutter:
    sdk: flutter

  digit_components: ^0.0.2+1
  reactive_forms: ^14.1.0
  flutter_lints: ^2.0.0
  freezed: ^2.4.3
  build_runner: ^2.4.6
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
